import type { ScanReport } from "./types";

export const EXAMPLE_REPORT: ScanReport = {
  id: "example",
  url: "https://api.github.com",
  hostname: "api.github.com",
  faviconUrl: "https://www.google.com/s2/favicons?domain=api.github.com&sz=128",
  scannedAt: "2026-06-28T12:00:00.000Z",
  overallScore: 93,
  grade: "A",
  responseTimeMs: 142,
  responseTimeLabel: "Excellent",
  statusCode: 200,
  contentType: "application/json",
  payloadSize: 2048,
  server: "GitHub.com",
  categories: {
    performance: {
      score: 100,
      findings: [
        "Fast response time (142ms).",
        "Response uses compression.",
      ],
    },
    security: {
      score: 79,
      findings: [
        "HTTPS enabled.",
        "X-Content-Type-Options header present.",
        "X-Frame-Options header present.",
        "Missing Content-Security-Policy header.",
        "Missing Referrer-Policy header.",
        "CORS allows all origins (*).",
      ],
    },
    apiQuality: {
      score: 100,
      findings: [
        "Successful status code (200).",
        "JSON content type detected.",
        "Valid JSON response body.",
      ],
    },
    bestPractices: {
      score: 95,
      findings: [
        "API versioning detected.",
        "Rate limit headers present.",
        "Cache-Control header present.",
        "No request ID header for tracing.",
      ],
    },
  },
  responsePreview: JSON.stringify(
    {
      current_user_url: "https://api.github.com/user",
      authorizations_url: "https://api.github.com/authorizations",
      code_search_url: "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
      emails_url: "https://api.github.com/user/emails",
      emojis_url: "https://api.github.com/emojis",
      events_url: "https://api.github.com/events",
      feeds_url: "https://api.github.com/feeds",
      followers_url: "https://api.github.com/user/followers",
      following_url: "https://api.github.com/user/following{/user}",
      gists_url: "https://api.github.com/gists{/gist_id}",
      hub_url: "https://api.github.com/hub",
      issues_url: "https://api.github.com/issues",
      keys_url: "https://api.github.com/user/keys",
      notifications_url: "https://api.github.com/notifications",
      organization_url: "https://api.github.com/orgs/{org}",
      public_gists_url: "https://api.github.com/gists/public",
      rate_limit_url: "https://api.github.com/rate_limit",
      repository_url: "https://api.github.com/repos/{owner}/{repo}",
      user_url: "https://api.github.com/users/{user}",
    },
    null,
    2,
  ),
  headers: {
    server: "GitHub.com",
    "content-type": "application/json; charset=utf-8",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "x-content-type-options": "nosniff",
    "x-frame-options": "deny",
    "x-ratelimit-limit": "60",
    "x-ratelimit-remaining": "59",
    "access-control-allow-origin": "*",
    "cache-control": "public, max-age=60, s-maxage=60",
    "x-github-api-version": "2022-11-28",
  },
};
